language: node_js
os: osx
node_js:
  - "node"
cache: yarn
before_script:
  - expo login -u $EXP_UNAME -p $EXP_PASSWORD
script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then expo p; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then expo p --release-channel staging; fi
after_script:
  - expo logout

branches:
  only:
    - master
    - develop
